### ISSUE TITLE
Add support for path and method based rate limiting for Routes

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#107]

**Comment by eguzki** [comment]
This does not make sense, does it? The route object does not have path or methods defined. So, it is hard to have custom rate limit description per route. 

The path and method based rate limited can be achieved by generating with virtualhost level actions description entries with the path and the method and then, limits based on path and method. All implemented with the RateLimitpolicy. Something like the following:

```yaml
---
apiVersion: apim.kuadrant.io/v1alpha1
kind: RateLimitPolicy
metadata:
  name: toystore
spec:
  rateLimits:
    - stage: PREAUTH
      actions:
        - request_headers:
            descriptor_key: "path"
            header_name: ":path"
        - request_headers:
            descriptor_key: "method"
            header_name: ":method"
  limits:
    - conditions: 
        - "method == GET"
        - "path == \"/toys\""
      max_value: 2
      namespace: toystore
      seconds: 10
      variables: []
```

I think we can close this issue
