### ISSUE TITLE
Add Kuadrant CRD and skeleton controller and reconcile

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#150]

**Comment by eguzki** [comment]
Already implemented.

CRD in [here](https://github.com/Kuadrant/kuadrant-operator/blob/ae8a68a61df5060e09e624cb1fee15c615b4cb88/bundle/manifests/kuadrant.kuadrant.io_kuadrants.yaml)

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: kuadrants.kuadrant.kuadrant.io
spec:
  group: kuadrant.kuadrant.io
  names:
    kind: Kuadrant
    listKind: KuadrantList
    plural: kuadrants
    singular: kuadrant
  scope: Namespaced
  ....
```

And Controller in [controllers/kuadrant_controller.go](https://github.com/Kuadrant/kuadrant-operator/blob/ae8a68a61df5060e09e624cb1fee15c615b4cb88/controllers/kuadrant_controller.go)

```go
// For more details, check Reconcile and its Result here:
// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.10.0/pkg/reconcile
func (r *KuadrantReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	_ = log.FromContext(ctx)

	// your logic here

	return ctrl.Result{}, nil
}
```
