### ISSUE TITLE
RateLimitPolicy and AuthPolicy rules proposal

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#190]
**What**

within RLP and AP, we have a rules section. I want to propose that we allow these to be empty and take the default values from the target resource. For AuthPolicy that would also include the hosts for the AuthConfig.

In RateLimitPolicy this would mean, the below would be applied to any host and path / method combination specified in the target HTTPRoute. When targeting a gateway it would apply to any host the gateway could handle. We can still allow the user to be more specific if they need to be, but this feels like a good default

```
apiVersion: apim.kuadrant.io/v1alpha1
kind: RateLimitPolicy
metadata:
  name: toystore-httproute
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rateLimits:
    - rules:
      configurations:
        - actions:
            - generic_key:
                descriptor_key: get-toy
                descriptor_value: "yes"
      limits:
        - conditions: ["get-toy == yes"]
          maxValue: 2
          seconds: 30
          variables: []

```

AuthPolicy could be created like this targeting a HTTPRoute with "api.toystore.com and admin.toystore" as its host but instead of repeating that information look like the below

```
piVersion: apim.kuadrant.io/v1alpha1
kind: AuthPolicy
metadata:
  name: toystore
  namespace: kuadrant-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: kuadrant-gwapi-gateway
  authScheme:
    identity:
      - name: apikey
        apiKey:
          labelSelectors:
            app: toystore
            admin: "yes"
        credentials:
          in: authorization_header
          keySelector: APIKEY
```

Then, if the end user needs to be more specific (IE only target admin.toystore.com) they can fill in the rules. Perhaps when taking the values from the target, we add that as detail to the status?
