### ISSUE TITLE
API Discovery

### ISSUE THREAD

**Issue by jmprusi** [Kuadrant/kuadrant-controller#28]
I'm working on implementing this concept as a PoC, but I would like to get some feedback! 

When adding a new application that contains an API, to reduce the number of objects that a user has to author,
we can leverage annotations. A good place to annotate could be the Service used to drive traffic to the application 
PODs.

You will recognize some of those from the "3scale discovery spec". 

### Annotations:

- **discovery.kuadrant.io/scheme**: *OPTIONAL* Either HTTP or HTTPS specifies how the kuadrant gateway will connect to this API.
- **discovery.kuadrant.io/api-name**: *OPTIONAL* If not set, the name of the API can be matched with the service name.
- **discovery.kuadrant.io/tag**: OPTIONAL A special tag used to distinguish this deployment between several instances of the API.
- **discovery.kuadrant.io/oas-path**:  Path where the OAS of the service is exposed. Kuadrant will contact the service and try to retrieve the OAS spec.
- **discovery.kuadrant.io/oas-configmap**: Configmap that contains the OAS spec.
- **discovery.kuadrant.io/port**: Only required if there are multiple ports in the service. Either the Name of the port or the Number.

Labels:
- **discovery.kuadrant.io/enabled:**: *REQUIRED* true or false, marks the object to be discovered by kuadrant.

Complete annotated Service example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: dogs-api
  annotations:
    discovery.kuadrant.io/scheme: "https"
    discovery.kuadrant.io/api-name: "dogs-api"
    discovery.kuadrant.io/tag: "production"
    discovery.kuadrant.io/oas-path: "/api/openapi/json"
  labels:
    discovery.kuadrant.io/enabled: "true"
spec:
  selector:
    app: dogs-api
  ports:
    - name: HTTP
      protocol: TCP
      port: 80
      targetPort: 9376
```

In case that the API is hosted outside the cluster, the developer can use the ExternalName service type, this way we keep only having to reconcile Services and not extra types. An example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: dogs-api
  annotations:
    discovery.kuadrant.io/scheme: "https"
    discovery.kuadrant.io/api-name: "dogs-api"
    discovery.kuadrant.io/tag: "production"
    discovery.kuadrant.io/oas-path: "/api/openapi/json"
  labels:
    discovery.kuadrant.io/enabled: "true"
spec:
  type: ExternalName
  externalName: my-remote-api.example.com
```

By providing that label and those annotations, the kuadrant controller should be able to pull the OAS spec, and generate an internal object (API) that will be useful for the other kuadrant components, and also, to have a proper snapshot of the state without having to rely on external resources.

That API object will look similar to this, pending implementation:

```yaml
apiVersion: networking.kuadrant.io/v1beta1
kind: API
metadata:
  name: dogs-api
spec:
  tags:
    - name: production
      APIDefinition:
        - OAS: |
             Inlined OAS spec.
      destination:
        serviceRef:
          name: dogs-api
          namespace: where-the-dogs-are
          port: 80
          schema: "https"
```

### Problems/Questions:

* We will get the OAS in the first reconcile run, but we need to define a way to find if the OAS has changed.. new PODs? New container image? Some basic polling? Only when the service gets touched/updated? 

* Is the externalName service type going to be enough? There are some edge cases that I'm not aware of, like DNS resolution issues or so? 

* Do we need to provide an alternative way to ship the OAS? A reference to a configmap/url?  -> Added the configmap version.

-- Updates (DD/MM/YY) ---
01/07/21: Added `discovery.kuadrant.io/oas-configmap` to the initial object. Already implemented in the actual codebase.

**Comment by guicassolato** [comment]
> We will get the OAS in the first reconcile run, but we need to define a way to find if the OAS has changed.. new PODs? New container image? Some basic polling? Only when the service gets touched/updated?

Not sure if `discovery.kuadrant.io/tag` can be used for versioning. If so, then this will do it, no? Or maybe adding `discovery.kuadrant.io/version` otherwise.

**Comment by jmprusi** [comment]
> > We will get the OAS in the first reconcile run, but we need to define a way to find if the OAS has changed.. new PODs? New container image? Some basic polling? Only when the service gets touched/updated?
> 
> Not sure if `discovery.kuadrant.io/tag` can be used for versioning. If so, then this will do it, no? Or maybe adding `discovery.kuadrant.io/version` otherwise.

The OAS can change, for example, by the deployment being modified with a new container image, or using `myimage:latest` and pushing a new image to the registry...  Usually, the service is untouched between deployments, but perhaps we can be opinionated there.

**Comment by guicassolato** [comment]
> The OAS can change, for example, by the deployment being modified with a new container image, or using myimage:latest and pushing a new image to the registry... Usually, the service is untouched between deployments, but perhaps we can be opinionated there.

I was thinking that, the first reconciliation will happen when the `Service` is first created or first annotated. IMO, it kind of makes sense that reconciling again depends on the `Service` object being as you said, "touched" by the owner of the resource. My suggestion before was more in the sense of _how_ to touch it, i.e., by updating the annotation.

**Comment by eguzki** [comment]
I miss from the service annotations the port of the oas:
`discovery.kuadrant.io/oas-port`

**Comment by jmprusi** [comment]
> I miss from the service annotations the port of the oas:
> `discovery.kuadrant.io/oas-port`

@eguzki I guess that can be a new "feature", the OAS spec living in a different port than the one used to serve the actual API traffic.

**Comment by jmprusi** [comment]
Ok, folks, we need to make a decision here.

Let's agree to go with reconciling the OAS on each service change? 

later we can keep investigating the proper way: pulling each X seconds, watching for container/pod changes, etc...

**Comment by eguzki** [comment]
Currently there is a way for the user to change the OAS and the kuadrant controller will reconcile the changes.

Let's say the user has deployed the following service:
```
apiVersion: v1
kind: Service
metadata:
  name: dogs-api
  annotations:
    discovery.kuadrant.io/scheme: "https"
    discovery.kuadrant.io/api-name: "dogs-api"
    discovery.kuadrant.io/tag: "production"
    discovery.kuadrant.io/oas-configmap: "cats-oas-v1"
  labels:
    discovery.kuadrant.io/enabled: "true"
spec:
  type: ExternalName
  externalName: my-remote-api.example.com
```

The user wants to update the OAS. The user can create a **new** configmap called `cats-oas-v2` with the new OAS content and update the Service:

```
apiVersion: v1
kind: Service
metadata:
  name: dogs-api
  annotations:
    discovery.kuadrant.io/scheme: "https"
    discovery.kuadrant.io/api-name: "dogs-api"
    discovery.kuadrant.io/tag: "production"
    discovery.kuadrant.io/oas-configmap: "cats-oas-v2" <- **NOTE** the change in the config map name
  labels:
    discovery.kuadrant.io/enabled: "true"
spec:
  type: ExternalName
  externalName: my-remote-api.example.com
```

Then, the kuadrant controller will reconcile the underlying API resource and then reconcile ingress provider configuration accordingly.

Still not implemented:
* When the OAS is exposed in the API in a path
* Watch the OAS ConfigMap for external changes
