### ISSUE TITLE
API Object changes for handling generic services.

### ISSUE THREAD

**Issue by jmprusi** [Kuadrant/kuadrant-controller#30]
### Why? 

Right now, kuadrant only covers API use-cases, but there's an opportunity to cover more high-value but simple scenarios. To do so, we need specific changes to the current "API" object.

#### Current object:

```yaml
apiVersion: networking.kuadrant.io/v1beta1
kind: API
metadata:
  name: dogs
  namespace: where-the-dogs-are
spec:
  tags:
    - name: production
      mappings:
        - OAS: |
             Inlined OAS spec.
      destination:
        serviceRef:
          name: dogs
          port: 80
          schema: "https"
```

#### Proposed changes:

```yaml
apiVersion: networking.kuadrant.io/v1beta1
kind: ServiceRegistration # New Object name to better reflect what this object is doing. 
metadata:
  name: myapi.production # Service/API name + "." + TAG, this way, we can remove the Tags array and avoid merging multiple tags into the same object.
spec:
  type: API # type could be either API or service. If the user doesn't provide an OAS annotation, the type will be "service."
  mappings:
    - OAS: |
     Inline OAS
  destination:
    serviceRef:
      name: dogs
      port: 80
      schema: "https"
```

Summary of changes:

- **Object name**: From "API" to "ServiceRegistration", to better reflect this object's intent.

- **Name**: The tag is appended to the object name instead of requiring an array. This simplifies authoring while keeping it easy to find all the related services/APIs. We can improve the discovery of the related objects by automatically adding some labels.

- **New field "Type"**: Used to define if an object is a service or an API. Sets the expectations for the controllers to validate/find information.

- **Removal of TAG array**: The sole purpose of tags was to have multiple definitions of the same service/API in a namespace. We can reuse the name field of k8s objects as it is unique and "automatically" enforced.

**Comment by eguzki** [comment]
* removal of `spec.tags` :+1: 
* Object new name :-1:  I would try to find other name. This is not a service and there is no registration action. `Backend`, `Upstream` would represent better. Maybe `ProtectedAPI` ? Anyway, it should be an internal resource with no external visibility.
* **Name** :-1:: It has more sense to use annotations for this purpose than having the *tag* or *environment* as part of the name. The name could have other dots `.` in the name as well which makes hard to *parse* the environment
* `spec.type` field: can you elaborate more on this? What use could the controller make of it?

**Comment by jmprusi** [comment]
> * removal of `spec.tags` 👍
> * Object new name 👎  I would try to find other name. This is not a service and there is no registration action. `Backend`, `Upstream` would represent better. Maybe `ProtectedAPI` ? Anyway, it should be an internal resource with no external visibility.

Well, its sole purpose is to register a service into Kuadrant, and I think it basically goes really well with the workflow... I would like to avoid the term API as we want to cover Non-API services. Backend/Upstream can express too many things in  too many different contexts.. 

> * **Name** 👎: It has more sense to use annotations for this purpose than having the _tag_ or _environment_ as part of the name. The name could have other dots `.` in the name as well which makes hard to _parse_ the environment

You can't create two objects with the same name and different annotations/labels.

As I said, we can actually add those labels/annotations too when the object is created by the kuadrant-controller automatically. But in order to have one service with multiple configurations, we need two different names.

In the case that the name has other dots, you just have to keep the latest one as the tag.

> * `spec.type` field: can you elaborate more on this? What use could the controller make of it?

If the object is marked as an API, the kuadrant controller will try to read the OAS spec, if the OAS is not available an error (status condition) should be returned to the user.  If the object is marked as a Service, the kuadrant-controller will not expect an OAS spec, if it's specified it can be a misconfiguration from the user, so we need to reject it. etc... 

Also, please keep in mind, that the Kuadrant controller is not the only controller that will make use of this object. Other components will need this extra information to actually represent/handle the object properly.

**Comment by eguzki** [comment]
> Well, its sole purpose is to register a service into Kuadrant, and I think it basically goes really well with the workflow... I would like to avoid the term API as we want to cover Non-API services. Backend/Upstream can express too many things in too many different contexts..

k8s resources represent states, not actions. 

> But in order to have one service with multiple configurations, we need two different names.

One service with multiple configurations? Why not one service per configuration? What is the definition of configuration in this context. As I understand, "configuration" means different OAS or served endpoints or different requests/responses. I would expect different service. Maybe something to take into account is having the same upstream service (or pod or external url) being represented by different "ServiceRegistration" resources.

> If the object is marked as an API, the kuadrant controller will try to read the OAS spec, if the OAS is not available an error (status condition) should be returned to the user. If the object is marked as a Service, the kuadrant-controller will not expect an OAS spec, if it's specified it can be a misconfiguration from the user, so we need to reject it. etc...

You are referring to different type of services like `gRPC` services? Then the `type` field may make sense. For "APIs" without OAS, I do not see a need for `type` field. Just structured `mappings` field:
For OAS based services:
```
mappings:
    OAS: 
      inline: |
           ....
      URL: "https://example.com/oas"
      configMap: 
         name: my-oas-configmap  
```

For services not providing OAS:

```
mappings:
   OAS: null,
   paths:
     "/cats":
         "get":
            description: "get cats"
```

**Comment by jmprusi** [comment]
> > Well, its sole purpose is to register a service into Kuadrant, and I think it basically goes really well with the workflow... I would like to avoid the term API as we want to cover Non-API services. Backend/Upstream can express too many things in too many different contexts..
> 
> k8s resources represent states, not actions.

A kubernetes object is a "record of intent" (desired state), and there are some objects that actually represent operations in the core API.

What about `Service`? It is a kuadrant service, so we can rename it to `service.networking.kuadrant.io`, and make it searchable via kubectl with `kuadrantsvc`.

> 
> > But in order to have one service with multiple configurations, we need two different names.
> 
> One service with multiple configurations? Why not one service per configuration? What is the definition of configuration in this context. As I understand, "configuration" means different OAS or served endpoints or different requests/responses. I would expect different service. Maybe something to take into account is having the same upstream service (or pod or external url) being represented by different "ServiceRegistration" resources.
> 

If two APIs in the same namespace, hold the same api-name annotation, then we will create two API object (or whatever the name) in the namespace, with the same api-name. this is not possible. appending the TAG to the API Objects names will solve this problem.

> > If the object is marked as an API, the kuadrant controller will try to read the OAS spec, if the OAS is not available an error (status condition) should be returned to the user. If the object is marked as a Service, the kuadrant-controller will not expect an OAS spec, if it's specified it can be a misconfiguration from the user, so we need to reject it. etc...
> 
> You are referring to different type of services like `gRPC` services? Then the `type` field may make sense. For "APIs" without OAS, I do not see a need for `type` field. Just structured `mappings` field:

No, I'm setting a field that basically tells the controller how to validate the object and what information it needs to retrieve in an explicit way. 

If the service type is API, get the OAS, if that's not there, fail and report to the user.
If the service type is "service", just expect one path, if there's an OAS report to the user.

A UI for example will be able to give different views of these objects based on that. 
Usage plans will be able to work with APIs, but not with services for example... 
And in the future it can be extended with different type of services is ever needed. 

But we can remove it, and we will figure it out in the future.

> For OAS based services:
> 
> ```
> mappings:
>     OAS: 
>       inline: |
>            ....
>       URL: "https://example.com/oas"
>       configMap: 
>          name: my-oas-configmap  
> ```
> 
> For services not providing OAS:
> 
> ```
> mappings:
>    OAS: null,
>    paths:
>      "/cats":
>          "get":
>             description: "get cats"
> ```

We should start by just allowing a base path (configurable via annotation, I will open an issue documenting this), as in a catch-all for the simple service type, if you want more advanced stuff (methods, paths..) define an OAS. Or we will end up creating yet another spec and having to document it, explain, authoring tools, etc.

**Comment by eguzki** [comment]
> What about Service? It is a kuadrant service, so we can rename it to service.networking.kuadrant.io, and make it searchable via kubectl with kuadrantsvc.

Looks good. Although, for me "UpstreamAPI" represents much better what it is.
> If two APIs in the same namespace, hold the same api-name annotation, then we will create two API object (or whatever the name) in the namespace, with the same api-name. this is not possible. appending the TAG to the API Objects names will solve this problem.

Yes, and if two customer services have the same annotations
```
discovery.kuadrant.io/api-name
discovery.kuadrant.io/tag
```
there will also be conflicts. 

For arbitrary names and in order to avoid collision, it is common to add suffix, for instance pods:
```
coredns-74ff55c5b-bmh6z        
coredns-74ff55c5b-k9nqf        
kindnet-b2tk7                  
kube-proxy-9b6rs               
```
We could do something like this, but then it may be harder to reference them from the APIProduct spec. I do not have strong opinion on this. We can start with whatever and then iterate further.

Regarding the `type` field. I just do not see a need to have some `type` field. Depending on the content of the `mappings` struct, the controller can do whatever. If OAS is found, use it. If one path is found do something else. Whether there is a OAS or one path does not depend on APIProduct controller, but in the Service controller or some other tool (CLI or UI bases client) creating the "API" (or whatever name) resources. If you think it is required, go ahead.

**Comment by jmprusi** [comment]
> > What about Service? It is a kuadrant service, so we can rename it to service.networking.kuadrant.io, and make it searchable via kubectl with kuadrantsvc.
> 
> Looks good. Although, for me "UpstreamAPI" represents much better what it is.
> 

I insist this object should be able to represent NON API services, that's why we are changing it's name, to better represent what it is.


> Yes, and if two customer services have the same annotations
> 
> ```
> discovery.kuadrant.io/api-name
> discovery.kuadrant.io/tag
> ```
> 
> there will also be conflicts.

No one should be able to create multiple APIS with the same `api-name` AND the same `tag` in a namespace. It's a unique combination, or we will not be able to actually reference it properly. 

But If you want to create multiple APIs that share the same `api-name`, with different `tags`, that should be possible.

> 
> For arbitrary names and in order to avoid collision, it is common to add suffix, for instance pods:
> 
> ```
> coredns-74ff55c5b-bmh6z        
> coredns-74ff55c5b-k9nqf        
> kindnet-b2tk7                  
> kube-proxy-9b6rs               
> ```
> 
> We could do something like this, but then it may be harder to reference them from the APIProduct spec. I do not have strong opinion on this. We can start with whatever and then iterate further.

using `generateName` could work, while still referencing the API from the APIProduct with name and tag, as we can use certain labels to find the proper object etc... Sadly, doing a `kubectl get` will show weird names, and authoring the API object manually will require you to add labels. let's keep it simple.

> 
> Regarding the `type` field. I just do not see a need to have some `type` field. Depending on the content of the `mappings` struct, the controller can do whatever. If OAS is found, use it. If one path is found do something else. Whether there is a OAS or one path does not depend on APIProduct controller, but in the Service controller or some other tool (CLI or UI bases client) creating the "API" (or whatever name) resources. If you think it is required, go ahead.

But that's implicit knowledge: "If this is missing then I guess..."

If you don't see any value in this, let's just ignore it for now. We can always add it or just encapsulate this in a method of the object (getType())

**Comment by jmprusi** [comment]
After some talks, let's keep it simple:

- Don't change the object names.
- Get rid of the tag array
- If the service specifies a Tag annotation, put that tag as part of the API name.
- Tags will no longer be required. If not, set API object name == api-name or service name, depending on the annotations.
- No "type" field.
- For simple services with no OAS, we include a single [HTTPPathMatch](https://gateway-api.sigs.k8s.io/references/spec/#networking.x-k8s.io/v1alpha1.HTTPPathMatch) field so that users can define a specific path or a catch-all prefix.

```yaml
apiVersion: networking.kuadrant.io/v1beta1
kind: ServiceRegistration # New Object name to better reflect what this object is doing. 
metadata:
  name: myapi.production # Service/API name + "." + TAG, this way, we can remove the Tags array and avoid merging multiple tags into the same object.
spec:
  mappings:        # One of
    OAS: |
      Inline OAS
    HTTPPathMatch:
      path: /
      type: prefix # prefix or exact.
  destination:
    serviceRef:
      name: dogs
      port: 80
      schema: "https"
```
