### ISSUE TITLE
If I delete an API object, but i still have the annotatons on the service what is the expected behaviour?

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#60]
If I have  a service with the following meta 

```
kind: Service
metadata:
  annotations:
    discovery.kuadrant.io/matchpath: /v1
    discovery.kuadrant.io/oas-configmap: toystore
  labels:
    discovery.kuadrant.io/enabled: "true"

```
an API object toystore is created. If I delete the API Object it is not re-created. Is this expected or should the object get recreated? If the trigger is ``` discovery.kuadrant.io/enabled: "true" ``` it would seem reasonable that it would get re-created or the delete prevented?

I can take a look at this depending on what we would want the behaviour to be.

- Remove label from service and the api from any apiProducts?
- Recreate API?
- Fail the delete if the label is present and set to true?
