### ISSUE TITLE
Adding Ratelimiting to the same gateway causes multiple requests to Limitador

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#71]
If you add two APIProducts with authenticated rate limiting a request to 1 endpoint will trigger 2 requests to limitador. 1 for each rate limit filter added at the gateway level. The number of requests will grow proportional to the number of filters added.

**Steps**

- create two echo apis
- label them with the discovery label
- add two api products

```
apiVersion: networking.kuadrant.io/v1beta1
kind: APIProduct
metadata:
  name: bookstore
  namespace: default
spec:
  hosts:
    - bookstore.127.0.0.1.nip.io
  APIs:
    - name: bookstore
      namespace: default
  securityScheme:
    - name: MyAPIKey
      apiKeyAuth:
        location: authorization_header
        name: APIKEY
        credential_source:
          labelSelectors:
            secret.kuadrant.io/managed-by: authorino
            api: toystore
  rateLimit:
    authenticated:
      maxValue: 3
      period: 5


apiVersion: networking.kuadrant.io/v1beta1
kind: APIProduct
metadata:
  name: toystore
  namespace: default
spec:
  hosts:
    - toystore.127.0.0.1.nip.io
  APIs:
    - name: toystore
      namespace: default
  securityScheme:
    - name: MyAPIKey
      apiKeyAuth:
        location: authorization_header
        name: APIKEY
        credential_source:
          labelSelectors:
            secret.kuadrant.io/managed-by: authorino
            api: toystore
  rateLimit:
    authenticated:
      maxValue: 1
      period: 5

```

make a single request to the bookstore in the limitador logs you will see it is called for both domains:

``` 
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Settings { flags: (0x0), initial_window_size: 1048576, max_frame_size: 16384 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::proto::connection] Connection; peer=Server
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Settings { flags: (0x0), header_table_size: 4096, enable_push: 0, max_concurrent_streams: 2147483647, initial_window_size: 268435456 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Settings { flags: (0x1: ACK) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 268369921 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Settings { flags: (0x1: ACK) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::proto::settings] received settings ACK; applying Settings { flags: (0x0), initial_window_size: 1048576, max_frame_size: 16384 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 983041 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG limitador_server::envoy_rls::server] Request received: Request { metadata: MetadataMap { headers: {"te": "trailers", "grpc-timeout": "20m", "content-type": "application/grpc", "x-b3-traceid": "2fe576109219495397a1b57aaa15c5ff", "x-b3-spanid": "2c2b33a7d145a8b1", "x-b3-parentspanid": "97a1b57aaa15c5ff", "x-b3-sampled": "0", "x-envoy-internal": "true", "x-forwarded-for": "10.244.0.8", "x-envoy-expected-rq-timeout-ms": "20"} }, message: RateLimitRequest { domain: "bookstore.default", descriptors: [RateLimitDescriptor { entries: [Entry { key: "user_id", value: "alice" }] }], hits_addend: 0 }, extensions: Extensions }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(1) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Data { stream_id: StreamId(3), flags: (0x1: END_STREAM) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG limitador_server::envoy_rls::server] Request received: Request { metadata: MetadataMap { headers: {"te": "trailers", "grpc-timeout": "20m", "content-type": "application/grpc", "x-b3-traceid": "2fe576109219495397a1b57aaa15c5ff", "x-b3-spanid": "b5cf1278e05acd55", "x-b3-parentspanid": "97a1b57aaa15c5ff", "x-b3-sampled": "0", "x-envoy-internal": "true", "x-forwarded-for": "10.244.0.8", "x-envoy-expected-rq-timeout-ms": "20"} }, message: RateLimitRequest { domain: "toystore.default", descriptors: [RateLimitDescriptor { entries: [Entry { key: "user_id", value: "alice" }] }], hits_addend: 0 }, extensions: Extensions }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(3) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(3), flags: (0x5: END_HEADERS | END_STREAM) }

```

**Comment by maleck13** [comment]
One option here would be to have a single entry for the rate limiting filter in the gateway and add a unique condition to each limit based on the api product

**Comment by eguzki** [comment]
I have reproduced the test and this is somewhat annoying. Why the rate limit domain (some arbitrary value), is defined at a HTTP filter level where the request is not being filtered at domain/hostname level? The rendered envoy listener config looks like this:
```yaml
configs:
  - '@type': type.googleapis.com/envoy.admin.v3.ListenersConfigDump.DynamicListener
    name: 0.0.0.0_8080
    active_state:
      version_info: 2022-01-12T15:13:25Z/5
      listener:
        '@type': type.googleapis.com/envoy.config.listener.v3.Listener
        name: 0.0.0.0_8080
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
          - filters:
              - name: envoy.filters.network.http_connection_manager
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  stat_prefix: outbound_0.0.0.0_8080
                  rds:
                    config_source:
                      ads: {}
                      resource_api_version: V3
                    route_config_name: http.80
                  http_filters:
                    - (previous filters)
                    - name: envoy.filters.http.postauth.ratelimit
                      typed_config:
                        '@type': type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                        domain: toystore.default
                        stage: 1
                        failure_mode_deny: true
                        rate_limit_service:
                          grpc_service:
                            envoy_grpc:
                              cluster_name: rate_limit_cluster
                            timeout: 3s
                          transport_api_version: V3
                    - name: envoy.filters.http.postauth.ratelimit
                      typed_config:
                        '@type': type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                        domain: bookstore.default
                        stage: 1
                        failure_mode_deny: true
                        rate_limit_service:
                          grpc_service:
                            envoy_grpc:
                              cluster_name: rate_limit_cluster
                            timeout: 3s
                          transport_api_version: V3
```

I see two options. 

One is as you describe. A single RL http filter. But then the rate limit domain does not play any role. Kuadrant needs to define custom rate limit descriptor entry to filter at RL service with a condition. Kuadrant cannot do this transparently for the customer as the customer is the owner of the rate limit config at the service. 

The other option is adding a rule to filter by domain (authority header) the HTTP filter itself, as it is being done with the `ext_auth` http filter. 

```yaml
- name: envoy.filters.http.rbac
  typed_config:
    '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
    shadow_rules:
      action: DENY
      policies:
        istio-ext-authz-ns[kuadrant-system]-policy[bookstoredefault]-rule[0]:
          permissions:
            - and_rules:
                rules:
                  - or_rules:
                      rules:
                        - header:
                            name: :authority
                            prefix_match: 'bookstore.127.0.0.1.nip.io:'
                        - header:
                            name: :authority
                            exact_match: bookstore.127.0.0.1.nip.io
          principals:
            - and_ids:
                ids:
                  - any: true
        istio-ext-authz-ns[kuadrant-system]-policy[toystoredefault]-rule[0]:
          permissions:
            - and_rules:
                rules:
                  - or_rules:
                      rules:
                        - header:
                            name: :authority
                            prefix_match: 'toystore.127.0.0.1.nip.io:'
                        - header:
                            name: :authority
                            exact_match: toystore.127.0.0.1.nip.io
          principals:
            - and_ids:
                ids:
                  - any: true
- name: envoy.filters.http.ext_authz
  typed_config:
    '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
    grpc_service:
      envoy_grpc:
        cluster_name: outbound|50051||authorino-authorization.kuadrant-system.svc.cluster.local
        authority: outbound_.50051_._.authorino-authorization.kuadrant-system.svc.cluster.local
      timeout: 600s
    transport_api_version: V3
    filter_enabled_metadata:
      filter: envoy.filters.http.rbac
      path:
        - key: shadow_effective_policy_id
      value:
        string_match:
          prefix: istio-ext-authz
```

I have not tried this second option, but looks the most promising, but still ugly. Ugly because, IMO, the rate limit domain should be defined at the level where rate limit actions are defined (at routeconfiguration level)
